<template>
  <div>
    <h1>Is this real or fake?</h1>
    <h2>Some pictures are real people.</h2>
    <h2>Some pictures are fake(generated by our learning model).</h2>
    <van-image 
     square
    width="20rem"
    height="20rem"
    :src="this.srcString"
    class="app"
  />
  <h1 v-on:click="guessreal">real</h1>
  <h1 v-on:click="guessfake">fake</h1>
  <h1 v-if="tag" v-on:click='submit'>submit</h1>
   </div>
</template>

<script>
import { Image as VanImage } from 'vant';
import axios from 'axios';
export default {
  name: 'App',
  components: {
    VanImage
  },
  methods:{
  guessreal(){
    this.index=this.index+1
    if (this.index==10)
      this.tag=true
    this.srcString=this.list[this.index].url
    this.ans.push(1)
  },
   guessfake(){
    this.index=this.index+1
    if (this.index==10)
      this.tag=true
    this.srcString=this.list[this.index].url
    this.ans.push(0)
  },
  submit(){
    let that=this
   axios.post('/api/submit_answers', JSON.stringify(
     {
    task_id: that.taskid
  }),
  {headers:{
    'Content-Type':'application/json'
  }

  })
  .then(function (response) {
    console.log(response);
  })
  .catch(function (error) {
    console.log(error);
  });
  }
  },
  created() {
  // Simple GET request using axios
  this.uuid = this.$route.query.id
  console.log(this.myuuid)
  let that =this
  axios.get("/api/get_images?number=10",)
    .then(response => {that.list = response.data.list, that.taskid=response.data.task_id,that.srcString=that.list[0].url});
},
 
  data() {
    return {
      url:'',
      index:0,
      list:[],
      ans:[],
      myuuid:this.$route.query.id,
      headimg: require("../assets/logo.png"),
      srcString:'',
      tag:false
      
    }
  }
}
</script>

<style>

</style>
