<template>
  <div>
    <h1>Is this real or fake?</h1>
    <h2>Some pictures are real people.</h2>
    <h2>Some pictures are fake(generated by our learning model).</h2>
    <van-image
    square
    width="20rem"
    height="20rem"
    :src="srcString"
    class="app"
  />
   </div>
</template>

<script>
import { Image as VanImage } from 'vant';

export default {
  name: 'App',
  components: {
    VanImage
  },
  data() {
    return {
      headimg: require("../assets/logo.png"),
      srcString: "../assets/logo.png"
    }
  }
}
</script>

<style>

</style>
