<template>
<div>
  <h1>Is this real or fake?</h1>
  <h2>Some pictures are real people.</h2>
  <h2>Some pictures are fake(generated by our learning model).</h2>
  <van-image
  square
  width="20rem"
  height="20rem"
  :src="srcString"
  class="app"
/>


  

 </div>

  
</template>

<script>
// import HelloWorld from './components/HelloWorld.vue'
// import Vue from 'vue';
import { Image as VanImage } from 'vant';


export default {
  name: 'App',
  components: {
    // HelloWorld
    VanImage
  },
  data(){
    return {
      headimg: require("./assets/logo.png"),
      srcString: "./assets/logo.png"
    }
          
   }
  
  
}
</script>

<style>
#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
  margin-top: 60px;
}
</style>
